### ISSUE TITLE
`POST_HOOK_RETURN` hook is not being called under certain conditions

### ISSUE THREAD

**Issue by luca1197** [Srlion/Hook-Library#11]
Sorry in advance for the potentially confusing description, it took me quite a while to isolate the issue, but I think I was able to create a reproduction.

Given the following hooks (all hooking the same event):
* Hook A (`POST_HOOK_RETURN`) which does anything (in this case just a debug print)
* Hook B (`NORMAL_HOOK`) which returns a value

When I then create another hook (Hook C [`NORMAL_HOOK`]) and remove this hook C, hook A is not called anymore. Hook B is still being called and returns its value. When hook B stops returning a value, hook A is called again.

The expected behavior would be that hook A is still called with the return value from hook B, like it did before hook C existed.

The following reproduction example uses `CalcView` but it also happens to (all?) other events (I tried `PlayerBindPress` and the issue was the same). To reproduce the issue, run the following console commands in order:
1. `srilonhook_test_condition_b`
2. `srilonhook_test_add_c`
3. `srilonhook_test_remove_c`

After that, only hook B prints to the console. When running `srilonhook_test_condition_b` again, hook A starts printing to console but hook B does not anymore.
<details>

<summary>Reproduction code (Tested using latest library version)</summary>

```lua
hook.Add("CalcView", "srilonhook_test_A", function(hookResult)

	print("Hook A CalcView", hookResult[1])

end, POST_HOOK_RETURN)


local condition = false

hook.Add("CalcView", "srilonhook_test_B", function(ply, pos, angles, fov)

	if condition then

		print("Hook B CalcView")
		
		-- When changing this to not return anything, everything works as expected
		local view = {
			origin = pos - ( angles:Forward() * 100 ),
			angles = angles,
			fov = fov,
			drawviewer = true
		}

		return view
		
	end

end)

concommand.Add("srilonhook_test_condition_b", function()

	condition = not condition
	
	chat.AddText("Condition is now: " .. tostring(condition))

end)


concommand.Add("srilonhook_test_add_c", function()

	hook.Add("CalcView", "srilonhook_test_C", function()

		print("Hook C CalcView")

	end)

end)


concommand.Add("srilonhook_test_remove_c", function()

	hook.Remove("CalcView", "srilonhook_test_C")

end)
``` 

</details>

During testing I always re-joined the game after doing any changes to make sure it doesn't temporarily fixes itself from hot-reloading the file / re-adding the hooks.

It would be awesome if this could be fixed since it prevents me from implementing a feature in an addon I was working on. Thanks a lot in advance. :)

Also thank you in general for the library, it's better than the ULib hook library I previously used in many ways, even though sometimes I'm a bit frustrated when some specific behavior changes between updates haha

**Comment by Srlion** [comment]
Thank you for your detailed issue, great to see them. Hopefully this commit I pushed fixes it.

**Comment by Srlion** [comment]
@luca1197 I have pushed a new update that refactors the whole library, test it and tell me if it has any issues. It should be more stable than before as code is easier to work with.

**Comment by luca1197** [comment]
@Srlion Sorry for the late response, I haven't had enough time in the last few days to test it on my prod server.

Everything seems to be working very well with the latest version, and the original issue is still fixed as well.

Thanks a lot for your great work!

**Comment by Srlion** [comment]
Great to hear!
